import json,re,html,os,random
pairs=json.load(open('/mnt/data/gre-vocab/pairs.json'))

# Phrase -> template. Templates contain {w} as a blank concept, never the actual word.
rules=[
 (['become less','lessen','make worse or less effective','weaker','less effective'], 'After the treatment, the pain gradually began to ___.', ['abate','alleviate','attenuate']),
 (['tricks to deceive','tricks','deceive','hoax'], 'The scheme relied on elaborate ___ to fool unsuspecting customers.', ['chicanery','dupe']),
 (['widely known','widely'], 'The university launched a campaign to ___ its findings beyond the country.', ['disseminate']),
 (['take exception','disagree'], 'The historian publicly ___ the claim, arguing that the evidence did not support it.', ['gainsay']),
 (['potentially existing','not presently evident'], 'The young researcher showed ___ talent that only became obvious years later.', ['latent']),
 (['different from an accepted norm','deviating'], 'The unusually high reading was ___ and prompted the technicians to rerun the test.', ['aberrant','anomalous']),
 (['liquid to','thickened','solid state'], 'As the sauce cooled, it began to ___ into a thick paste.', ['coagulate']),
 (['separation into component','separation'], 'The agreement led to the ___ of the organization into two independent groups.', ['dissolution']),
 (['trivial conversation'], 'At the party, his endless ___ about minor details exhausted everyone around him.', ['garrulous','loquacious']),
 (['praise','glorify','honor'], 'Critics continued to ___ the scientist for her groundbreaking work.', ['laud']),
 (['cessation','suspension'], 'The negotiations were placed in ___ until both sides could review the proposal.', ['abeyance']),
 (['closing section of a musical','closing section'], 'The composer added a short ___ that brought the symphony to a final close.', ['coda']),
 (['disagreeable sounds','unpleasant sound'], 'The audience winced as the instruments produced a harsh, ___ mix of notes.', ['dissonance','discordant','cacophonous']),
 (['urge on','pointed stick'], 'The coach kept trying to ___ the hesitant runner to give one final push.', ['goad']),
 (['alertness or activity','inactive'], 'After the long flight, she felt too ___ to do any serious work.', ['lethargic']),
 (['run away','taking something'], 'The accountant vanished overnight after secretly taking the company funds and deciding to ___.', ['abscond']),
 (['powerfully persuasive'], 'The lawyer presented a ___ argument backed by several independent studies.', ['cogent']),
 (['expand as if by internal pressure'], 'The balloon continued to ___ as more air was pumped into it.', ['distend']),
 (['impression in a surface','blow'], 'The falling branch left a deep ___ in the wooden door.', ['gouge']),
 (['embankment','river from overflowing'], 'The town strengthened its ___ before the river rose during monsoon season.', ['levee']),
 (['temperance','indulgence'], 'Even at celebrations, she was remarkably ___ and rarely drank more than a single glass.', ['abstemious']),
 (['corresponding in size','degree or extent'], 'The bonus should be ___ with the amount of extra work employees completed.', ['commensurate']),
 (['condensation'], 'The vapor was cooled so that it could ___ into a liquid.', ['distill']),
 (['lofty in style'], 'The speech was so ___ that ordinary people struggled to understand what the speaker meant.', ['grandiloquent']),
 (['lacking seriousness','not serious'], 'His comments about the crisis were full of ___ and annoyed the people trying to solve it.', ['levity']),
 (['scold','reprimand'], 'The principal had to ___ the students for repeatedly ignoring the safety rules.', ['admonish']),
 (['variety of works','collection'], 'The handbook is a useful ___ of essays on economics, history, and politics.', ['compendium']),
 (['move or draw apart','apart'], 'As the roads left the village, they began to ___ toward different valleys.', ['diverge']),
 (['company of others','sociable'], 'Unlike his quiet brother, he is extremely ___ and loves meeting strangers.', ['gregarious']),
 (['trunk of a tree'], 'A fallen ___ blocked the hiking trail after the storm.', ['log']),
 (['make impure','foreign or inferior substance'], 'The inspectors discovered that the company had ___ the milk with cheaper ingredients.', ['adulterate']),
 (['cheerful willingness','favors'], 'Her ___ attitude made her happy to help every new colleague who asked.', ['complaisant']),
 (['take away possessions'], 'The bankrupt investor was forced to ___ many of his assets.', ['divest']),
 (['innocent','free of deceit'], 'The child was completely ___ and trusted everyone she met.', ['guileless','artless']),
 (['appreciation of beauty','good taste'], 'The gallery hired her for her strong ___ sense and eye for design.', ['aesthetic']),
 (['accordance with someone','wishes'], 'The assistant was highly ___ and followed the director’s instructions without resistance.', ['compliant']),
 (['representation','symbolic marks'], 'The archaeologists found a clay tablet containing a written ___ of the trade agreement.', ['document']),
 (['naive','easily deceived'], 'Because he trusted strangers too quickly, the ___ traveler lost money to the scam.', ['gullible']),
 (['clear','easily understandable'], 'Her explanation was so ___ that even beginners understood the complicated process.', ['lucid']),
 (['sum total','taken together'], 'The report presents the ___ cost of transportation, labor, and materials.', ['aggregate']),
 (['making concessions','make concessions'], 'The mediator adopted a ___ tone to help the two sides reach a compromise.', ['conciliatory']),
 (['code of beliefs','authoritative'], 'The professor was so ___ that she dismissed any evidence that challenged her theory.', ['dogmatic']),
 (['loud bombastic declamation','strong emotion'], 'The senator launched into a furious ___ against the proposed law.', ['harangue','tirade','diatribe']),
 (['softly bright','radiant'], 'The lantern gave off a warm, ___ glow in the dark room.', ['luminous']),
 (['liveliness and eagerness'], 'She accepted the difficult assignment with surprising ___ and got started immediately.', ['alacrity']),
 (['excuse','overlook'], 'The coach would not ___ repeated lateness, even when the players apologized.', ['condone']),
 (['inactive but capable','becoming active'], 'The volcano had been ___ for centuries, but scientists still monitored it closely.', ['dormant']),
 (['same or similar kind'], 'The classroom contained a remarkably ___ group of students with nearly identical backgrounds.', ['homogeneous']),
 (['nobility and generosity'], 'He showed great ___ by forgiving the rival who had publicly insulted him.', ['magnanimity']),
 (['confusing or perplexing'], 'The contradictory instructions only served to ___ the new employees.', ['confound']),
 (['extravagant exaggeration'], 'Saying that the minor delay had ruined his entire life was obvious ___.', ['hyperbole']),
 (['shirking duty','feigning illness'], 'The supervisor suspected the employee was a ___ because he suddenly claimed to be ill whenever work increased.', ['malingerer']),
 (['combine together'], 'The two companies decided to ___ their operations into a single organization.', ['amalgamate','incorporate']),
 (['expert able to appreciate'], 'Only a wine ___ could distinguish the subtle differences between the two bottles.', ['connoisseur']),
 (['joyously unrestrained'], 'The crowd became ___ when the final score was announced.', ['ebullient']),
 (['attack on established beliefs'], 'Her ___ research challenged several assumptions that other scholars had treated as sacred.', ['iconoclastic']),
 (['shaped or bent','malleable'], 'The metal is so ___ that workers can bend it without breaking it.', ['malleable']),
 (['more than one possible meaning'], 'The wording of the contract was ___, so each side interpreted it differently.', ['ambiguous']),
 (['competing','profit or prize'], 'The two teams were locked in fierce ___ for the championship.', ['contention']),
 (['various styles or ideas'], 'Her reading list was ___, ranging from ancient philosophy to modern physics.', ['eclectic']),
 (['worship of objects','images as gods'], 'The reformer condemned the practice of treating sacred statues as divine objects, calling it ___.', ['idolatry']),
 (['independence in thought'], 'The ___ scientist ignored the fashionable theory and pursued her own explanation.', ['maverick']),
 (['mixed feelings','emotions'], 'He felt ___ about moving abroad: excited by the opportunity but sad to leave home.', ['ambivalence']),
 (['inclination to disagree'], 'The committee became so ___ that even minor wording changes led to arguments.', ['contentious']),
 (['capacity or power','desired result'], 'The drug’s ___ was tested by comparing recovery rates with those of a placebo.', ['efficacy']),
 (['not subject','change or variation'], 'The law was considered ___, so even a national emergency could not alter it.', ['immutable']),
 (['given to lying'], 'Because he was known to be ___, reporters checked every statement against independent records.', ['mendacious']),
 (['feeling or expressing pain','sorrow'], 'The defendant appeared genuinely ___ after realizing how badly his actions had hurt others.', ['contrite']),
 (['audacious behavior','no right'], 'His ___ shocked everyone: he walked into the private meeting without an invitation and demanded a seat.', ['effrontery']),
 (['worse or less effective'], 'The outdated software began to ___ the computer’s performance.', ['impair']),
 (['striking change in appearance','character'], 'The caterpillar undergoes a dramatic ___ before emerging as a butterfly.', ['metamorphosis']),
 (['at a time when','couldn’t have existed'], 'The movie contains an obvious ___: a modern smartphone appears in a scene set in 1920.', ['anachronism']),
 (['difficult problem'], 'The committee faced a difficult ___ with no solution that satisfied everyone.', ['conundrum']),
 (['mournful poem','lament for the dead'], 'The poet wrote an ___ after the death of her close friend.', ['elegy']),
 (['little emotion','little sensibility'], 'Even when the audience gasped, the detective remained completely ___ and continued taking notes.', ['impassive','stolid']),
 (['precise accordance with details'], 'Her ___ attention to every decimal place caught the error that everyone else had missed.', ['meticulous']),
 (['similar or equivalent'], 'The two experiments produced ___ results despite using different methods.', ['analogous']),
 (['come together'], 'The two railway lines ___ near the city center.', ['converge']),
 (['call forth','emotion','response'], 'The speaker’s story was designed to ___ sympathy from the audience.', ['elicit']),
 (['hindrance or obstacle'], 'Heavy traffic continued to ___ emergency vehicles on their way to the hospital.', ['impede']),
 (['dislikes people'], 'The retired professor became something of a ___, avoiding parties and refusing invitations.', ['misanthrope']),
 (['lawlessness and disorder'], 'After the government collapsed, the region descended into ___ and violence.', ['anarchy']),
 (['complex or intricate'], 'The tax code was so ___ that even experts struggled to follow its logic.', ['convoluted']),
 (['more attractive','ornament or color'], 'The designer used gold trim to ___ the otherwise simple room.', ['embellish']),
 (['preventing liquids','pass or diffuse'], 'The container is made of an ___ material that keeps water completely out.', ['impermeable']),
 (['seriousness or extent','lessen'], 'The new safety measures should ___ the risk of accidents.', ['mitigate']),
 (['experiment and observation'], 'The researchers based their conclusion on ___ evidence gathered from thousands of tests.', ['empirical']),
 (['extreme calm','composure'], 'Even during the crisis, the pilot remained ___ and spoke calmly to the passengers.', ['imperturbable','equanimity']),
 (['favorably inclined','appease'], 'The diplomat offered concessions in an attempt to ___ the angry officials.', ['mollify','appease','placate','propitiate']),
 (['intense dislike'], 'She felt a strong ___ toward the company after it had treated her family unfairly.', ['antipathy']),
 (['lose courage'], 'The size of the opposing team did not ___ the young players.', ['daunt']),
 (['equal or match','imitating'], 'The student tried to ___ her mentor’s success by adopting the same disciplined routine.', ['emulate']),
 (['not admitting of passage','affected'], 'The material is ___ to water, so even heavy rain cannot penetrate it.', ['impervious']),
 (['brooding ill humor'], 'He spent the afternoon in a ___ mood, barely speaking to anyone.', ['morose']),
 (['absence of emotion','enthusiasm'], 'Her ___ toward the election surprised her friends, who expected her to care deeply.', ['apathy']),
 (['manners and conduct'], 'The diplomats maintained perfect ___ throughout the tense negotiations.', ['decorum','propriety']),
 (['native to','confined to a certain region'], 'The disease is ___ to a small island and rarely occurs elsewhere.', ['endemic']),
 (['incapable of being appeased','pacified'], 'The judge faced an ___ critic who refused every compromise.', ['implacable']),
 (['ordinary course of events'], 'For most office workers, answering routine emails is a ___ part of the day.', ['mundane']),
 (['option selected automatically'], 'If you do not choose a setting, the system will use the ___ option.', ['default']),
 (['weaken physically','mentally','morally'], 'Weeks of sleep deprivation began to ___ the normally energetic students.', ['enervate']),
 (['suggested though not directly expressed'], 'Her criticism was ___; she never named him, but everyone knew whom she meant.', ['implicit']),
 (['make ineffective'], 'The witness’s new evidence could ___ the prosecution’s main argument.', ['negate']),
 (['inform somebody'], 'The manager called to ___ the staff of the change in schedule.', ['apprise']),
 (['courteous regard'], 'Out of ___ for the elderly guests, the organizers kept the music at a reasonable volume.', ['deference']),
 (['call forth'], 'The policy may ___ resentment among workers who feel ignored.', ['engender']),
 (['burst inward'], 'The metal tank began to ___ when the pressure inside dropped suddenly.', ['implode']),
 (['no experience','activity'], 'As a ___ to academic research, she spent the first few months learning basic methods.', ['neophyte']),
 (['official acceptance','agreement'], 'The proposal received formal ___ from the board after several revisions.', ['approbation']),
 (['accurately or precisely'], 'The diagram was carefully drawn to ___ the structure of the machine.', ['delineate']),
 (['increase'], 'A fresh coat of paint can ___ the appearance of an old room.', ['enhance']),
 (['without knowledge or intention'], 'He ___ deleted the file while trying to reorganize the folder.', ['inadvertently']),
 (['stubbornly persistent'], 'Despite repeated warnings, the ___ tenant refused to follow the building rules.', ['obdurate']),
 (['suitable for'], 'Please choose clothing that is ___ for a formal interview.', ['appropriate']),
 (['attack the good name'], 'The article attempted to ___ the scientist by questioning her motives rather than her evidence.', ['denigrate','disparage']),
 (['short-lived'], 'The online trend was ___, disappearing almost as quickly as it became popular.', ['ephemeral']),
 (['partly in existence','imperfectly formed'], 'The proposal remained ___, with no clear plan for how to implement it.', ['inchoate']),
 (['win favor','flattery'], 'The assistant’s ___ compliments became obvious once she started asking the director for special treatment.', ['obsequious','fawning']),
 (['effort to the point of exhaustion'], 'Climbing the mountain was an ___ task that took two full days.', ['arduous']),
 (['contempt'], 'The critics continued to ___ the amateur performance instead of offering constructive advice.', ['deride']),
 (['steadiness of mind under stress'], 'She handled the emergency with remarkable ___, never raising her voice.', ['equanimity']),
 (['quality of disagreeing'], 'The obvious ___ between the modern building and its historic neighbors made it stand out.', ['incongruity']),
 (['do away with'], 'The new system was designed to ___ the need for paper forms.', ['obviate']),
 (['deliberately ambiguous'], 'When reporters asked for a yes-or-no answer, the politician chose to ___.', ['equivocate','prevaricate']),
 (['lacking worth','importance'], 'The difference was so ___ that no one thought it worth discussing further.', ['inconsequential']),
 (['block passage'], 'A buildup of debris could ___ the narrow pipe and stop the water supply.', ['occlude']),
 (['self denial','spiritual discipline'], 'The monk practiced an ___ lifestyle, owning almost nothing and eating very simply.', ['ascetic']),
 (['lacking vitality','lifeless'], 'Without water, the plants became dry and ___ within days.', ['desiccate']),
 (['profound knowledge'], 'The ___ scholar could discuss ancient languages without consulting a reference book.', ['erudite']),
 (['intrusive','meddling'], 'His ___ habit of correcting everyone’s work quickly annoyed the entire team.', ['officious']),
 (['care and persistent effort'], 'Her ___ preparation meant she checked every source before submitting the report.', ['assiduous']),
 (['lack of definite plan','purpose','enthusiasm'], 'Their search was ___, with no clear destination and little sense of urgency.', ['desultory']),
 (['inner circle','specialized'], 'The paper used such ___ terminology that only a handful of specialists could understand it.', ['esoteric']),
 (['not fixed or known in advance'], 'Because demand was unpredictable, the final cost remained ___.', ['indeterminate']),
 (['burdensome','difficult to endure'], 'The paperwork had become so ___ that employees spent hours filling out forms.', ['onerous']),
 (['interferes with action','progress'], 'The high registration fee became a major ___ for students from low-income families.', ['deterrent']),
 (['formal expression of praise','died'], 'At the memorial, her former students delivered a moving ___ describing her influence.', ['eulogy']),
 (['extreme poverty','destitution'], 'The charity provides food and housing to people living in extreme ___.', ['indigence','penury']),
 (['extreme dishonor'], 'The official resigned after the scandal brought widespread ___ upon the institution.', ['opprobrium']),
 (['thunderous verbal attack'], 'The editorial was a furious ___ against corruption in the government.', ['diatribe','invective','tirade']),
 (['inoffensive expression','offensive'], 'Instead of saying that he had been fired, the company used the ___ “position eliminated.”', ['euphemism']),
 (['disinclined to work'], 'He was so ___ that he preferred to postpone simple tasks until the deadline was close.', ['indolent']),
 (['swing from side to side','regularly'], 'The pendulum continued to ___ between the two positions.', ['oscillate','vacillate']),
 (['venture or take risks'], 'The ___ climber attempted the route that more cautious teams had avoided.', ['audacious']),
 (['two opposed parts'], 'The debate presented a false ___ between economic growth and environmental protection.', ['dichotomy']),
 (['make worse'], 'Adding more delays would only ___ the already serious problem.', ['exacerbate']),
 (['unable to move'], 'The heavy machine remained completely ___ after its motor failed.', ['inert']),
 (['attract notice','impress others'], 'The billionaire arrived in an ___ car covered with custom gold detailing.', ['ostentatious']),
 (['stern or strict'], 'The monastery had an ___ atmosphere, with strict rules and little decoration.', ['austere']),
 (['lack of self-assurance'], 'Her ___ made her hesitate to speak even when she knew the answer.', ['diffidence']),
 (['pronounce not guilty'], 'The new evidence may ___ the suspect by showing he was elsewhere.', ['exculpate']),
 (['liver or meat','minced','seasoned'], 'The chef prepared a rich pâté from finely minced meat and herbs.', ['pate']),
 (['lacking sophistication','worldliness'], 'His ___ approach to negotiation made him easy for experienced dealers to manipulate.', ['ingenuous']),
 (['perfect embodiment'], 'She is regarded as a ___ of patience and professionalism.', ['paragon']),
 (['independent entity'], 'The colony eventually became politically ___ from the empire.', ['autonomous']),
 (['spread out','not concentrated'], 'The population is widely ___ across the region rather than clustered in cities.', ['diffuse']),
 (['pressing or urgent situation'], 'In an ___, the hospital can activate its emergency response team immediately.', ['exigency']),
 (['essential constituent','characteristic'], 'Curiosity is an ___ part of scientific thinking.', ['inherent']),
 (['fervent','militant proponent'], 'He became a fierce ___ of the reform and defended it at every meeting.', ['partisan','zealot']),
 (['declare or affirm solemnly'], 'Under oath, the witness ___ that he had never met the defendant.', ['aver']),
 (['departs from the main subject'], 'The speaker went on a long ___ about childhood memories that had nothing to do with the proposal.', ['digression']),
 (['inference about future','known facts'], 'The forecast was an ___ based on current population and spending trends.', ['extrapolation']),
 (['not injurious','harmless'], 'The chemical is generally ___ in small quantities, so the lab workers do not need protective suits.', ['innocuous']),
 (['study of diseases'], 'The doctor consulted a ___ report to understand how the disease was progressing.', ['pathological']),
 (['overfamiliar through overuse'], 'The slogan sounded ___ because audiences had heard similar phrases for decades.', ['banal','platitude']),
 (['song or hymn of mourning'], 'The choir sang a solemn ___ at the funeral.', ['dirge']),
 (['cleverly amusing'], 'His ___ remark earned a few laughs but failed to hide the seriousness of the situation.', ['facetious']),
 (['barely able to be perceived'], 'The old radio signal was so faint that it was almost ___.', ['insensible']),
 (['insufficient quantity','number'], 'A ___ of volunteers meant the organizers could not open all the planned booths.', ['paucity']),
 (['contradiction'], 'Her cheerful smile seemed to ___ the sadness she had described moments earlier.', ['belie']),
 (['erroneous belief'], 'The teacher worked to ___ the students of the misconception that the exam had been canceled.', ['disabuse']),
 (['make easier'], 'The new software will ___ communication between hospitals.', ['facilitate']),
 (['suggest indirectly','covert'], 'The article seemed to ___ that the company had hidden the evidence, without saying so directly.', ['insinuate']),
 (['narrow focus','display of learning'], 'His ___ correction of every minor grammatical detail irritated the rest of the class.', ['pedantic']),
 (['doing or producing good'], 'The foundation is known for its ___ work in rural communities.', ['beneficent']),
 (['keen insight','good judgment'], 'A ___ editor quickly noticed that the statistics did not support the headline.', ['discerning']),
 (['incorrect reasoning'], 'The conclusion was ___ because it relied on a false assumption about cause and effect.', ['fallacious']),
 (['lacking interest','significance','impact'], 'The lecture was so ___ that half the audience stopped taking notes.', ['insipid']),
 (['strong liking','preference'], 'She has a pronounced ___ for historical novels over contemporary fiction.', ['penchant']),
 (['support and strengthen'], 'The new data helped ___ the researchers’ original conclusion.', ['bolster']),
 (['not in agreement','harmony'], 'The two reports were ___, giving completely different accounts of the incident.', ['discordant']),
 (['devoid of intelligence'], 'The proposal was so ___ that even its author struggled to explain the basic idea.', ['fatuous']),
 (['lack of openness','narrow-mindedness'], 'Years spent in a single intellectual community gave him an unfortunate sense of ___.', ['insularity']),
 (['held in low esteem'], 'The repeated scandals brought the once-respected agency into ___.', ['discredit']),
 (['difficult to manage','mold'], 'The child was bright but so ___ that every attempt at discipline failed.', ['intractable']),
 (['lasting indefinitely'], 'The company faced a ___ shortage of skilled workers unless it changed its training program.', ['perennial']),
 (['ill-mannered','coarse'], 'The guest’s ___ jokes offended nearly everyone at the dinner.', ['boorish']),
 (['difference between conflicting facts'], 'There was a significant ___ between the two copies of the contract.', ['discrepancy']),
 (['agreeably appropriate','style'], 'The novelist’s choice of words was especially ___ and suited the mood perfectly.', ['felicitous']),
 (['stubborn refusal','compromise'], 'Their ___ made it impossible for the negotiations to move forward.', ['intransigence']),
 (['betray'], 'The spy was accused of a ___ act after secretly selling information to the enemy.', ['perfidious']),
 (['grow and flourish'], 'The small business began to ___ once the new product reached international markets.', ['burgeon']),
 (['separate entity','part'], 'The two experiments were treated as ___ studies rather than one combined project.', ['discrete']),
 (['great warmth','intensity'], 'The fans cheered with such ___ that the players could hear them from the tunnel.', ['fervor']),
 (['fill or cover completely','water'], 'Heavy rain began to ___ the streets, forcing residents onto higher ground.', ['inundate']),
 (['hasty','without attention to detail'], 'The inspector gave the building only a ___ glance before signing the form.', ['perfunctory']),
 (['polish and make shiny'], 'The jeweler carefully ___ the silver before placing it in the display case.', ['burnish']),
 (['not straightforward','candid'], 'His answer sounded ___ because he avoided admitting what he had actually done.', ['disingenuous']),
 (['rectangular piece of cloth','design'], 'A large national ___ hung from the balcony during the ceremony.', ['flag']),
 (['tough by habitual exposure'], 'After years of working outdoors, she had become ___ to heat and cold.', ['inured']),
 (['allowing fluids','gases to pass'], 'The fabric is ___, allowing air to circulate while keeping the texture light.', ['permeable','porous']),
 (['support','stone or brick'], 'The old cathedral needed a massive stone ___ to keep the wall from collapsing.', ['buttress']),
 (['unaffected by concern for own welfare'], 'As an impartial mediator, she remained ___ and focused only on a fair outcome.', ['disinterested']),
 (['young bird','flying'], 'The ___ struggled to balance on the branch during its first attempts at flight.', ['fledgling']),
 (['abusive language'], 'The article contained so much ___ that readers could barely find any substantive criticism.', ['invective']),
 (['spread throughout'], 'Mobile phones have become ___ in everyday life.', ['pervasive']),
 (['taken apart at connections'], 'The report felt ___, with facts from different sections appearing in random order.', ['disjointed']),
 (['contemptuous disregard'], 'Drivers who ___ the speed limit put everyone else at risk.', ['flout']),
 (['quickly aroused to anger'], 'Because he was so ___, even a mild criticism could trigger an argument.', ['irascible']),
 (['showing little emotion'], 'The actor delivered the tragic news in an unusually ___ tone.', ['phlegmatic']),
 (['chance or impulse','rather than necessity'], 'The CEO made a ___ decision to launch the product early simply because she felt like it.', ['capricious','whimsical']),
 (['stop associating'], 'The club decided to ___ members who repeatedly violated its code of conduct.', ['dismiss']),
 (['stir up'], 'The pamphlets were designed to ___ anger against the new government.', ['foment']),
 (['uncertain how to act'], 'The committee remained ___ and could not decide which proposal to support.', ['irresolute']),
 (['religiously devout'], 'Her daily prayers and charitable work reflected deep ___.', ['piety']),
 (['verbal punishment'], 'The newspaper’s harsh ___ of the company damaged its public image.', ['castigation']),
 (['keep from happening','make impossible'], 'The early warning system could ___ a much larger disaster.', ['forestall']),
 (['line of travel','access'], 'The travel guide included a detailed ___ covering museums, trains, and hotels.', ['itinerary']),
 (['initiates or accelerates chemical reaction'], 'Adding the catalyst caused the reaction to proceed much faster.', ['catalyst']),
 (['fundamentally different'], 'The two studies reached opposite conclusions because they examined ___ populations.', ['disparate']),
 (['avoiding waste'], 'Her ___ habits allowed the family to save money without feeling deprived.', ['frugality']),
 (['brief and to the point'], 'His answer was so ___ that the interview ended in less than ten minutes.', ['laconic']),
 (['physically malleable'], 'The clay’s ___ allows artists to reshape it many times before it dries.', ['plasticity']),
 (['destroying by chemical action'], 'The cleaner is highly ___ and can burn through metal if left on too long.', ['caustic']),
 (['affectedly','unnaturally'], 'He began to ___ when the interviewer asked a question he did not want to answer.', ['dissemble']),
 (['producing no result'], 'The team realized that continuing to argue was ___ and decided to leave.', ['futile']),
 (['lack of interest or energy'], 'After weeks without rest, she was overcome by ___ and could barely concentrate.', ['lassitude']),
 (['trite or obvious remark'], '“Everything happens for a reason” sounded like a tired ___.', ['platitude']),
 (['extreme excess'], 'The buffet offered such a ___ of desserts that guests could not try them all.', ['plethora']),
 (['cancel officially'], 'The agency voted to ___ the outdated regulation.', ['rescind']),
 (['scattered or unpredictable'], 'Rainfall has been ___ this year, with long dry spells interrupted by sudden storms.', ['sporadic']),
 (['easily managed'], 'The new software is simple and ___, even for inexperienced users.', ['tractable']),
 (['drop sharply'], 'Stock prices began to ___ after the company announced the failed merger.', ['plummet']),
 (['violation of law','duty','moral principle'], 'The judge described the theft as a serious ___ of public trust.', ['transgression']),
 (['full of holes'], 'The old sponge is highly ___ and absorbs water quickly.', ['porous']),
 (['command against'], 'The law was passed to ___ the sale of the chemical to private buyers.', ['proscribe']),
 (['find a solution'], 'The engineers met late into the night to ___ the technical problem.', ['resolve']),
 (['sparingly','restricted quantities'], 'During the drought, the authorities had to ___ water to households.', ['stint']),
 (['defiant aggressiveness'], 'The officer was surprised by the suspect’s ___ response to a routine question.', ['truculence']),
 (['practical matters'], 'Her ___ approach focused on what could actually be accomplished with the available budget.', ['pragmatic']),
 (['strong and sharp taste or smell'], 'The curry had a ___ aroma that filled the entire kitchen.', ['pungent']),
 (['reluctant to draw attention'], 'The usually ___ scientist avoided interviews and let the research speak for itself.', ['reticent']),
 (['express demand or provision in agreement'], 'The contract ___ that all payments must be made within thirty days.', ['stipulate']),
 (['undecided'], 'He continued to ___ between accepting the job and staying where he was.', ['vacillate']),
 (['preliminary introduction'], 'The constitution begins with a brief ___ explaining its purpose.', ['preamble']),
 (['meeting proper standards'], 'Only applicants who are fully ___ may sit for the advanced examination.', ['qualified']),
 (['profound respect'], 'The students spoke in a ___ tone when discussing their former teacher.', ['reverent']),
 (['regard with respect'], 'Many generations continue to ___ the poet as a national treasure.', ['venerate']),
 (['not secure','beset with difficulties'], 'The bridge was in a ___ condition after years without maintenance.', ['precarious']),
 (['evade the truth','irrelevant objections'], 'Instead of answering the question, the witness began to ___ over minor details.', ['quibble']),
 (['mentor in spiritual and philosophical topics'], 'The young student sought advice from a respected ___ who had spent decades studying ethics.', ['sage']),
 (['marked with stripes'], 'The scientist examined a ___ rock surface under the microscope.', ['striate']),
 (['habitually speaking truth'], 'Her reputation as a ___ witness made the jury more willing to trust her testimony.', ['veracious']),
 (['bring about abruptly'], 'The sudden announcement helped ___ a change in company policy.', ['precipitate']),
 (['quiet or still or inactive'], 'The lake remained ___ at dawn, with barely a ripple on its surface.', ['quiescent']),
 (['promoting health'], 'The mountain air was considered especially ___ for people recovering from respiratory illness.', ['salubrious']),
 (['walk in proud confident way'], 'He entered the room with a theatrical ___ that made everyone look up.', ['strut']),
 (['too many words'], 'The report was accurate but unnecessarily ___, repeating the same point in several sections.', ['verbose']),
 (['indicating approach'], 'A sudden drop in temperature can be a ___ of an approaching storm.', ['precursor']),
 (['high moral or intellectual value'], 'The retreat was held in a ___ environment devoted to advanced research and philosophy.', ['rarefied']),
 (['official permission','approval'], 'The project cannot begin until it receives official ___ from the regulator.', ['sanction']),
 (['compel attendance of witness'], 'The court issued a ___ requiring the witness to appear and testify.', ['subpoena']),
 (['capable of life','growth'], 'The biologists debated whether the damaged plant was still ___ or beyond recovery.', ['viable']),
 (['going beyond appropriate','courteous'], 'It was ___ of him to demand a personal favor from someone he had just met.', ['presumptuous']),
 (['resistant to authority','control'], 'The ___ teenager ignored every instruction given by the school administration.', ['recalcitrant','refractory']),
 (['fill to satisfaction'], 'After the large meal, everyone was fully ___ and did not want dessert.', ['satiate']),
 (['wear off','die down'], 'The noise from the crowd began to ___ after the final speaker left.', ['subside']),
 (['high resistance to flow'], 'Honey is more ___ than water and therefore pours much more slowly.', ['viscous']),
 (['formally reject','disavow'], 'The politician was forced to ___ the controversial remarks made by an aide.', ['recant']),
 (['fill completely'], 'The sponge quickly became ___ with water.', ['saturate']),
 (['establish with evidence'], 'The researchers needed additional data to ___ their surprising claim.', ['substantiate']),
 (['harshly abusive criticism'], 'The review was so ___ that it seemed designed to insult rather than evaluate the film.', ['vituperative']),
 (['immaculately clean','unused'], 'The museum displayed the newly discovered manuscript in ___ condition.', ['pristine']),
 (['lives in solitude'], 'The writer became a ___, rarely leaving the remote house where he worked.', ['recluse']),
 (['taste or smell','appealing'], 'The soup had a smoky ___ that lingered pleasantly on the palate.', ['savor']),
 (['take the place'], 'Digital payments have begun to ___ cash for many everyday purchases.', ['supersede']),
 (['sudden change or violence'], 'The situation remained ___, with prices changing dramatically from hour to hour.', ['volatile']),
 (['complete integrity'], 'The judge was respected for his ___ and refusal to accept bribes.', ['probity']),
 (['difficult to understand'], 'The professor’s explanation was so ___ that even advanced students needed to reread it.', ['recondite']),
 (['generate and separate from cells'], 'Certain glands ___ hormones directly into the bloodstream.', ['secrete']),
 (['conjecturing'], 'Without direct evidence, the explanation remained a mere ___ about what might have happened.', ['supposition']),
 (['incapable of being justified'], 'The accusation was completely ___ because there was no evidence supporting it.', ['unwarranted']),
 (['making great mental demands'], 'The advanced proof was so ___ that students needed several hours to work through it.', ['problematic']),
 (['broken piece'], 'The archaeologist found a pottery ___ near the ancient wall.', ['shard']),
 (['implied','inferred from actions'], 'Although no one said it aloud, there was a ___ agreement that the meeting was over.', ['tacit']),
 (['keen caution','watchful'], 'Investors remained ___ after the market’s sudden decline.', ['wary']),
 (['recklessly wasteful'], 'His ___ spending left him with almost no savings despite earning a high salary.', ['prodigal']),
 (['overthrow by argument'], 'The new experiment helped ___ the earlier theory.', ['refute']),
 (['habitually doubts'], 'As a ___, she asked for evidence before accepting the surprising claim.', ['skeptic']),
 (['superficial relevance'], 'His comment about the restaurant was ___ to the discussion of climate policy.', ['tangential']),
 (['confused multitude'], 'The archive contained a confusing ___ of notes, letters, receipts, and photographs.', ['welter']),
 (['great depth'], 'The submarine descended into a ___ trench far below the ocean surface.', ['profound']),
 (['lower position'], 'After repeated mistakes, the player was ___ to the reserve team.', ['relegate']),
 (['anxiety and concern'], 'The nurse was ___ about the patient and checked on him repeatedly.', ['solicitous']),
 (['lacking substance','significance'], 'The evidence for the theory was so ___ that few researchers found it convincing.', ['tenuous']),
 (['discourage by price'], 'The hotel’s ___ rates made it inaccessible to most students.', ['prohibitive']),
 (['express criticism'], 'The editor used the final paragraph to ___ the company for misleading customers.', ['reproach']),
 (['inducing sleep'], 'The doctor warned that the medicine could have a ___ effect.', ['soporific']),
 (['violent denunciation'], 'The politician ended the debate with an angry ___ against his opponents.', ['tirade']),
 (['grow rapidly'], 'Online misinformation can ___ when people share sensational stories without checking them.', ['proliferate']),
 (['without moral scruples'], 'The novel’s villain is a charming but completely ___ businessman.', ['reprobate']),
 (['plausible but false'], 'The advertisement made a ___ claim that sounded scientific but had no evidence behind it.', ['specious']),
 (['motor and mental inactivity'], 'After taking the medication, he slipped into a state of ___ and barely moved.', ['torpor']),
 (['natural inclination'], 'She has a strong ___ toward mathematics and solves puzzles for fun.', ['propensity']),
 (['refuse to recognize as valid'], 'The board voted to ___ the agreement after discovering that it had been signed under false pretenses.', ['repudiate']),
 (['broad range'], 'The exhibition covered a broad ___ of artistic styles from realism to abstraction.', ['spectrum']),
 (['repeated turns and bends'], 'The hikers followed a ___ mountain road that twisted around the cliffs.', ['tortuous']),
]

# word-specific hint mapping from candidates
word_to_hint={}
for keys, template, words in rules:
    for w in words:
        word_to_hint[w]=template

# fallback families
fallback_templates=[
 'The committee’s decision was described this way because it involved a situation in which ___ became especially important.',
 'After reviewing the evidence, the experts agreed that the situation could best be described as ___ in nature.',
 'The reporter used this term after observing a situation in which the people involved ___ rather than taking a simpler course.',
 'The example was unusual enough that the researchers chose this term to describe what they observed: ___.',
]

def fallback(defn, word):
    d=defn.lower()
    # Try lexical paraphrase with sentence-specific slots
    if 'someone who' in d:
        return 'Everyone in the group avoided the person who fit this description: ___.'.replace('this description','that description')
    if d.startswith('a ') or d.startswith('an '):
        return 'The article described a situation that matched this idea: ___.'.replace('matched this idea','matched this description')
    if 'the state of' in d:
        return 'After the setback, the team found itself in a state where ___.'.replace('where','')
    return f"In the example, the subject was described in this way because it involved a situation where {d}."

for p in pairs:
    w=p['word']; d=p['definition']
    p['hint']=word_to_hint.get(w, fallback(d,w))

# Remove duplicate-rule candidates issue: a few words may have a better later rule.
# Specific corrections where fallback or earlier template is awkward.
corrections={
 'document':'The historian uncovered a written record that preserved the details of the agreement.',
 'dupe':'The scammer tried to ___ the elderly customer into paying for a worthless product.',
 'default':'Because she made no selection, the computer automatically chose the standard setting.',
 'problematic':'The advanced proof posed a serious challenge and required the students to rethink several assumptions.',
 'pathological':'The laboratory examined diseased tissue under a microscope to understand what had gone wrong.',
 'flag':'During the ceremony, the national banner was raised above the stage.',
 'pate':'The chef spread a smooth mixture of finely minced liver and spices onto the toast.',
 'striate':'Under the microscope, the rock surface showed clear parallel stripes.',
 'savor':'She paused to enjoy the rich smoky taste of the soup before taking another spoonful.',
 'log':'A fallen section of tree trunk blocked the narrow forest path.',
 'precursor':'A sudden rise in small tremors was an early sign that a larger earthquake might be approaching.',
 'qualified':'Only applicants who had met every academic requirement were allowed to take the exam.',
 'sanction':'The construction project could not begin until the regulator granted official approval.',
}
for p in pairs:
    if p['word'] in corrections: p['hint']=corrections[p['word']]

open('/mnt/data/gre-vocab/words.json','w').write(json.dumps(pairs,ensure_ascii=False,indent=2))
print('words',len(pairs),'mapped',sum(1 for p in pairs if p['word'] in word_to_hint))
